//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IconicFund.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual StudIconicFund.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IconicFund.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully..
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than or equal 1..
        /// </summary>
        public static string AllowedValueGT1 {
            get {
                return ResourceManager.GetString("AllowedValueGT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Must be Greater Than 18.
        /// </summary>
        public static string BirthDateValidation {
            get {
                return ResourceManager.GetString("BirthDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Code Already Exists..
        /// </summary>
        public static string CodeAlreadyExists {
            get {
                return ResourceManager.GetString("CodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Sent To.
        /// </summary>
        public static string CodeSentTo {
            get {
                return ResourceManager.GetString("CodeSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Commercial Registration Number is already exists.
        /// </summary>
        public static string CommercialRegistrationNoAlreadyExists {
            get {
                return ResourceManager.GetString("CommercialRegistrationNoAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation must match the new Password.
        /// </summary>
        public static string ConfirmPasswordNotMatched {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتعهد بصحة جميع البيانات والمستندات الرسمية المرفقة وأتحمل المسؤولية الكاملة في حال ثبت خلاف ذلك.
        /// </summary>
        public static string confirmtheDatavalidity {
            get {
                return ResourceManager.GetString("confirmtheDatavalidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create this record..
        /// </summary>
        public static string CreateFailure {
            get {
                return ResourceManager.GetString("CreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been created successfully..
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be Greater Than Today.
        /// </summary>
        public static string DateGreaterThanDateNow {
            get {
                return ResourceManager.GetString("DateGreaterThanDateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this record?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete this record, There are items related to it..
        /// </summary>
        public static string DeleteFailure {
            get {
                return ResourceManager.GetString("DeleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting This Request Will Delete Related Data Are you Sure Of Deleting It ?.
        /// </summary>
        public static string DeleteRequestConfirmation {
            get {
                return ResourceManager.GetString("DeleteRequestConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been deleted successfully..
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t edit this record..
        /// </summary>
        public static string EditFailure {
            get {
                return ResourceManager.GetString("EditFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been updated successfully..
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Already Exists.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No Exist.
        /// </summary>
        public static string EmployeeNoIsExist {
            get {
                return ResourceManager.GetString("EmployeeNoIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End DateMust Exceed StatDate.
        /// </summary>
        public static string EndDateMustExceedStartDate {
            get {
                return ResourceManager.GetString("EndDateMustExceedStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully..
        /// </summary>
        public static string FileUploadSuccess {
            get {
                return ResourceManager.GetString("FileUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Has Related Data.
        /// </summary>
        public static string HasRelatedData {
            get {
                return ResourceManager.GetString("HasRelatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This accound is inactive..
        /// </summary>
        public static string InactiveAccount {
            get {
                return ResourceManager.GetString("InactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password is Not Correct.
        /// </summary>
        public static string InCorrectPassword {
            get {
                return ResourceManager.GetString("InCorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InCorrect User Name.
        /// </summary>
        public static string InCorrectUserName {
            get {
                return ResourceManager.GetString("InCorrectUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Code..
        /// </summary>
        public static string InvalidCaptchaCode {
            get {
                return ResourceManager.GetString("InvalidCaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile Number.
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number must be 10 digits.
        /// </summary>
        public static string InvalidNumberLength {
            get {
                return ResourceManager.GetString("InvalidNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Server to Access Your Location.
        /// </summary>
        public static string LocationPERMISSION_DENIED {
            get {
                return ResourceManager.GetString("LocationPERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Password Sent To.
        /// </summary>
        public static string LoginPasswordSentTo {
            get {
                return ResourceManager.GetString("LoginPasswordSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Send Failed.
        /// </summary>
        public static string MessageSendFailed {
            get {
                return ResourceManager.GetString("MessageSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Mobile Number.
        /// </summary>
        public static string mobileNumber {
            get {
                return ResourceManager.GetString("mobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Already Exists.
        /// </summary>
        public static string MobileNumberAlreadyExists {
            get {
                return ResourceManager.GetString("MobileNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one..
        /// </summary>
        public static string MustSelectOne {
            get {
                return ResourceManager.GetString("MustSelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one role..
        /// </summary>
        public static string MustSelectRole {
            get {
                return ResourceManager.GetString("MustSelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Name Already Exist.
        /// </summary>
        public static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field Must Contain Arabic letters.
        /// </summary>
        public static string NameArabic {
            get {
                return ResourceManager.GetString("NameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field Must Contain English letters.
        /// </summary>
        public static string NameEnglish {
            get {
                return ResourceManager.GetString("NameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This national id already exists..
        /// </summary>
        public static string NationalIdAlreadyExists {
            get {
                return ResourceManager.GetString("NationalIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Id Must Be 10 Number Only.
        /// </summary>
        public static string NationalIdNumbers {
            get {
                return ResourceManager.GetString("NationalIdNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more attachments to add..
        /// </summary>
        public static string NoMoreAttachmentsToAdd {
            get {
                return ResourceManager.GetString("NoMoreAttachmentsToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more commitments to add..
        /// </summary>
        public static string NoMoreCommitmentsToAdd {
            get {
                return ResourceManager.GetString("NoMoreCommitmentsToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rules.
        /// </summary>
        public static string NoRules {
            get {
                return ResourceManager.GetString("NoRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Commercial Registration Number has been registered before..
        /// </summary>
        public static string NotUnique_CommercialRegistrationNo {
            get {
                return ResourceManager.GetString("NotUnique_CommercialRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers is allowed.
        /// </summary>
        public static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Successfully..
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Successfully..
        /// </summary>
        public static string RemoveSuccess {
            get {
                return ResourceManager.GetString("RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestActionSuccess.
        /// </summary>
        public static string RequestActionSuccess {
            get {
                return ResourceManager.GetString("RequestActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Code to Reset Password is: {0}.
        /// </summary>
        public static string ResetPasswordMessageBody {
            get {
                return ResourceManager.GetString("ResetPasswordMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password - Facilities Portal.
        /// </summary>
        public static string ResetPasswordMessageSubject {
            get {
                return ResourceManager.GetString("ResetPasswordMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule is added before in the same group..
        /// </summary>
        public static string RuleExists {
            get {
                return ResourceManager.GetString("RuleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully..
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Archive Title.
        /// </summary>
        public static string SearchByArchiveTitle {
            get {
                return ResourceManager.GetString("SearchByArchiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Category.
        /// </summary>
        public static string SearchByCategory {
            get {
                return ResourceManager.GetString("SearchByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Code.
        /// </summary>
        public static string SearchByCode {
            get {
                return ResourceManager.GetString("SearchByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Department Name.
        /// </summary>
        public static string SearchByDepartmentName {
            get {
                return ResourceManager.GetString("SearchByDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Email.
        /// </summary>
        public static string SearchByEmail {
            get {
                return ResourceManager.GetString("SearchByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Employee Number.
        /// </summary>
        public static string SearchByEmployeeNumber {
            get {
                return ResourceManager.GetString("SearchByEmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By EntryDate.
        /// </summary>
        public static string SearchByEntryDate {
            get {
                return ResourceManager.GetString("SearchByEntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Export Date.
        /// </summary>
        public static string SearchByExportDate {
            get {
                return ResourceManager.GetString("SearchByExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Exported Transaction No.
        /// </summary>
        public static string SearchByExportedTransactionNo {
            get {
                return ResourceManager.GetString("SearchByExportedTransactionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Exporting Title.
        /// </summary>
        public static string SearchByExportingTitle {
            get {
                return ResourceManager.GetString("SearchByExportingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Id.
        /// </summary>
        public static string SearchById {
            get {
                return ResourceManager.GetString("SearchById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Incoming Transaction No.
        /// </summary>
        public static string SearchByIncomingTransactionNO {
            get {
                return ResourceManager.GetString("SearchByIncomingTransactionNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By LastActionDate.
        /// </summary>
        public static string SearchByLastActionDate {
            get {
                return ResourceManager.GetString("SearchByLastActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Last Referred Date.
        /// </summary>
        public static string SearchByLastReferredDate {
            get {
                return ResourceManager.GetString("SearchByLastReferredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Last Referred To.
        /// </summary>
        public static string SearchByLastReferredTo {
            get {
                return ResourceManager.GetString("SearchByLastReferredTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Main Department Export No.
        /// </summary>
        public static string SearchByMainDepartmentExportNo {
            get {
                return ResourceManager.GetString("SearchByMainDepartmentExportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Mobile Number.
        /// </summary>
        public static string SearchByMobile {
            get {
                return ResourceManager.GetString("SearchByMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name.
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Phone Number.
        /// </summary>
        public static string SearchByPhoneNumber {
            get {
                return ResourceManager.GetString("SearchByPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Source Name.
        /// </summary>
        public static string SearchBySourceName {
            get {
                return ResourceManager.GetString("SearchBySourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Source Number.
        /// </summary>
        public static string SearchBySourceNumber {
            get {
                return ResourceManager.GetString("SearchBySourceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Title.
        /// </summary>
        public static string SearchByTitle {
            get {
                return ResourceManager.GetString("SearchByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Transaction ID.
        /// </summary>
        public static string SearchByTransactionID {
            get {
                return ResourceManager.GetString("SearchByTransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Department.
        /// </summary>
        public static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Priority.
        /// </summary>
        public static string SelectPriority {
            get {
                return ResourceManager.GetString("SelectPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Letter Type.
        /// </summary>
        public static string SelectReferredLetterType {
            get {
                return ResourceManager.GetString("SelectReferredLetterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source.
        /// </summary>
        public static string SelectSource {
            get {
                return ResourceManager.GetString("SelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Transaction.
        /// </summary>
        public static string SelectTransaction {
            get {
                return ResourceManager.GetString("SelectTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serach By Commercial Registration No.
        /// </summary>
        public static string SerachByCommercialRegistrationNo {
            get {
                return ResourceManager.GetString("SerachByCommercialRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Extension is ( png  - pdf - jpg -  jpeg- gif) only .
        /// </summary>
        public static string UnsupportedFileExtension {
            get {
                return ResourceManager.GetString("UnsupportedFileExtension", resourceCulture);
            }
        }
    }
}
